dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink@1.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.1/contracts'
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts'
      - '@chainlink/contracts=smartcontractkit/chainlink@1.2.1/contracts'